apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - clustermanagementaddon.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml

images:
  - name: quay.io/danateamorg/rcs-ocm-deployer
    newName: quay.io/danateamorg/rcs-ocm-deployer
    newTag: "latest"

patches:
  - target:
      kind: Deployment
      name: capp-status-sync-addon
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: capp-status-sync-addon
        namespace: open-cluster-management
      spec:
        template:
          spec:
            containers:
            - name: capp-status-sync-addon
              env:
              - name: ADDON_IMAGE
                value: quay.io/danateamorg/rcs-ocm-deployer:latest
