---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-capp
  failurePolicy: Fail
  name: capp.rcs.dana.io
  rules:
  - apiGroups:
    - rcs.dana.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - capp
  sideEffects: NoneOnDryRun
