apiVersion: v1
kind: Service
metadata:
  name: {{ include "rcs-ocm-deployer.fullname" . }}-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "rcs-ocm-deployer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "rcs-ocm-deployer.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 }}