apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "rcs-ocm-deployer.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "rcs-ocm-deployer.fullname" . }}-serving-cert
  labels:
  {{- include "rcs-ocm-deployer.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: {{ include "rcs-ocm-deployer.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-capp
  failurePolicy: Fail
  name: capp.validate.rcs.dana.io
  rules:
  - apiGroups:
    - rcs.dana.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - capps
  sideEffects: NoneOnDryRun