---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  - placementdecisions
  - placements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rcs.dana.io
  resources:
  - capps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rcs.dana.io
  resources:
  - capps/status
  verbs:
  - update
- apiGroups:
  - rcs.dana.io
  resources:
  - rcsconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - work.open-cluster-management.io
  resources:
  - manifestworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
