apiVersion: rcs.dana.io/v1alpha1
kind: Capp
metadata:
  name: capp-sahar22
spec:
  scaleMetric: cpu
  site: ocp-nikola
  configurationSpec:
    template:
      spec:
        containers:
          - image: docker.io/nginx
            name: sahar
            securityContext:
              runAsUser: 0
            env:
              - name: TARGET
                value: "Python Sample v1"
  routeSpec:
    hostname: sahardhagever.com
