apiVersion: rcs.dana.io/v1alpha1
kind: Capp
metadata:
  name: capp-sample2
spec:
  scaleMetric: cpu
  configurationSpec:
    template:
      spec:
        containers:
          - image: docker.io/{username}/helloworld-python
            name: sahar
            env:
              - name: TARGET
                value: "Python Sample v1"
  routeSpec:
    hostname: saharhagever
