name: lint
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Run vet
        run: go vet ./...