namespace: open-cluster-management

resources:
- manager.yaml
- clustermanagementaddon.yaml
- ../rbac

images:
- name: controller
  newName: controller
  newTag: latest

patches:
- path: addon_manager_env_var_patch.yaml

replacements:
  - source:
      kind: Deployment
      group: apps
      version: v1
      name: rcs-score-addon-manager
      fieldPath: .spec.template.spec.containers.0.image
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - .spec.template.spec.containers.0.env.0.value
        options:
          delimiter: '/'
          index: 0
          create: true
